import Head from "next/head";
import styles from "../styles/Home.module.css";

import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Auth Firebase Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Auth firebase next</h1>
        <br />
        <Link href="/login">
          <a className="text-center text-blue-700">Ingresar</a>
        </Link>
      </main>
    </div>
  );
}
